feat(impl):[TRI-1063] impl discovery service
catenax-ng/tx-item-relationship-service pull request #120
Opened 2023-01-30 12:32 UTC by ds-ext-kmassalski

Discovery service rest impl + mock impl.
Returning EDC base url or default address if not found

2023-01-30 14:54 UTC, ds-jkreutzfeld commented on ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcAddressResponse.java
> +    private List<String> connectorEndpoint;
Why should there be multiple endpoints for one BPN?

2023-01-30 14:54 UTC, ds-jkreutzfeld commented on ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryClient.java
> +    }
The default should be configurable as well.

2023-01-30 14:54 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RestTemplateConfig.java
> +            @Value("${bpdm.oAuthClientId}") final String clientRegistrationId) {
These entries are missing in the config, right?

2023-01-31 11:22 UTC, ds-ext-kmassalski commented on ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcAddressResponse.java
> +    private List<String> connectorEndpoint;
Based on documentation: https://confluence.catena-x.net/display/CORE/Dataspace+Discovery

2023-01-31 11:23 UTC, ds-ext-kmassalski commented on ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryFacade.java
> +    private static final String DEFAULT_EDC_ENDPOINT = "http://default";
We agreed to not use any defaults, but return "Unknown" status

2023-01-31 11:32 UTC, ds-ext-kmassalski commented on irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RestTemplateConfig.java
> +            @Value("${bpdm.oAuthClientId}") final String clientRegistrationId) {
Done, without charts. Is it enough or add it also there?

2023-01-31 13:10 UTC, ds-jkreutzfeld requested changes

2023-01-31 13:13 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RestTemplateConfig.java
> +            @Value("${bpdm.oAuthClientId}") final String clientRegistrationId) {
That's okay for now.

2023-01-31 17:30 UTC, merged

2023-01-31 17:43 UTC, ds-jhartmann commented
Merged by accident, wanted to merge my own PR, sorry!