feat(edc):[TRI-1064] Extract EDC components
catenax-ng/tx-item-relationship-service pull request #122
Opened 2023-01-31 18:56 UTC by ds-jkreutzfeld

EDC client code is now contained in a separate maven module, so it can be reused in the ESS implementation. It was necessary to also extract some shared code into a common module to avoid circular dependencies.

2023-02-01 16:12 UTC, ds-jhartmann requested changes
See individual comments.
In general: the following tests are failing with exception
 `java.util.NoSuchElementException: Unsupported AspectType: ASSEMBLY_PART_RELATIONSHIP. [...]`
- RelationshipDelegateTest
- IrsFunctionalTest
- IrsItemGraphQueryServiceSpringBootTest

OpenApi comparison fails as well

2023-02-01 16:37 UTC, ds-jkreutzfeld commented on edc-client/src/test/java/org/eclipse/tractusx/edc/CxTestDataAnalyzerTest.java
> +
Resolved

2023-02-01 16:38 UTC, ds-jkreutzfeld commented on edc-client/src/test/java/org/eclipse/tractusx/edc/CxTestDataAnalyzerTest.java
> +import static org.mockito.Mockito.mock;
Resolved

2023-02-01 16:40 UTC, ds-jkreutzfeld commented
> See individual comments. In general: the following tests are failing with exception `java.util.NoSuchElementException: Unsupported AspectType: ASSEMBLY_PART_RELATIONSHIP. [...]`
> 
> * RelationshipDelegateTest
> * IrsFunctionalTest
> * IrsItemGraphQueryServiceSpringBootTest
> 
> OpenApi comparison fails as well

The tests are fixed now, except for the OpenAPI comparison. This is due to the incomplete state of ess-dev, which was merged into this branch. As soon as that is fixed with https://github.com/catenax-ng/tx-item-relationship-service/pull/125, we can update this branch and the test will hopefully be green.

2023-02-02 10:46 UTC, ds-jkreutzfeld commented on edc-client/pom.xml
> +            <version>1.31</version>
Done :)

2023-02-02 12:11 UTC, ds-jhartmann approved these changes

2023-02-02 12:33 UTC, merged