feat(edc):[TRI-1064] Add notification support for EDC
catenax-ng/tx-item-relationship-service pull request #124
Opened 2023-02-01 11:37 UTC by ds-jkreutzfeld

2023-02-01 16:40 UTC, ds-jhartmann requested changes
Checkstyle and PMD issues. See individual comments. Everything else looks good.

2023-02-01 16:40 UTC, ds-jhartmann commented on edc-client/src/main/java/org/eclipse/tractusx/edc/EdcSubmodelClient.java
> +            final EdcNotification notification) throws EdcClientException;
Checkstyle error: redundant modifier 'final'

2023-02-01 16:40 UTC, ds-jhartmann commented on edc-client/src/main/java/org/eclipse/tractusx/edc/EdcSubmodelFacade.java
> +            throw new EdcClientException(cause);
PMD failure: Rule:PreserveStackTrace Priority:3 New exception is thrown in catch block, original stack trace may be lost.

2023-02-01 17:15 UTC, ds-jkreutzfeld commented on edc-client/src/main/java/org/eclipse/tractusx/edc/EdcSubmodelFacade.java
> +            throw new EdcClientException(cause);
Resolved

2023-02-01 17:15 UTC, ds-jkreutzfeld commented on edc-client/src/main/java/org/eclipse/tractusx/edc/EdcSubmodelClient.java
> +            final EdcNotification notification) throws EdcClientException;
Resolved

2023-02-02 07:42 UTC, ds-jhartmann approved these changes

2023-02-02 12:34 UTC, merged