chore(workflows):[TRI-1069] blacklisted and separated workflows
catenax-ng/tx-item-relationship-service pull request #138
Opened 2023-02-08 15:10 UTC by ds-mmaul

2023-02-08 16:23 UTC, ds-jhartmann requested changes

2023-02-08 16:23 UTC, ds-jhartmann commented on .github/workflows/irs-build.yml
Please keep the normal maven build `mvn clean verify --batch-mode`

2023-02-08 16:23 UTC, ds-jhartmann commented on .github/workflows/irs-build.yml
add the 'Cache maven packages' step here as well

2023-02-08 17:03 UTC, ds-mmaul commented on .github/workflows/irs-build.yml
readded the maven build step with run command `mvn clean verify --batch-mode`

2023-02-08 17:04 UTC, ds-mmaul commented on .github/workflows/irs-build.yml
added 'Cache maven packages' to the 'analyze with sonar'- workflow

2023-02-09 07:58 UTC, ds-jhartmann requested changes
One last thing

2023-02-09 07:58 UTC, ds-jhartmann commented on .github/workflows/irs-build.yml
> +    needs: build
You can remove the 'needs: build' requirement. Sonar scan is not dependent on the build job and they can run in parallel.

2023-02-09 09:10 UTC, ds-jhartmann requested changes

2023-02-09 09:10 UTC, ds-jhartmann commented on .github/workflows/irs-build.yml
> +    steps:
Please also add jdk 17

2023-02-09 09:14 UTC, ds-mmaul commented on .github/workflows/irs-build.yml
> +    steps:
added jdk 17

2023-02-09 09:24 UTC, ds-jhartmann approved these changes

2023-02-09 09:42 UTC, merged