feat: add charts to deploy full irs locally
catenax-ng/tx-item-relationship-service pull request #143
Opened 2023-02-13 09:23 UTC by emiladrianc

2023-02-17 08:30 UTC, ds-jkreutzfeld commented
I think that the Chart.lock file and the tar.gz files in charts/full-irs/charts/ should not be committed.

2023-02-17 08:48 UTC, ds-jkreutzfeld commented on charts/full-irs/templates/irs-digital-twin-registry-docker-secret.yaml
> +  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJaSE10YW1oaGNuUnRZVzV1T21kb2NGOU1aV1phTldnMlVqSlhVbVJJVW1Wa01YZ3lWRFZCZEhOVE4yOVZjV2N3ZG1zNFkzRT0ifX19
Secret committed! :(

2023-02-17 08:56 UTC, ds-jkreutzfeld commented
The test data files are now duplicated in the repository. Is there a way to pick them up from the original place?

2023-02-17 09:07 UTC, ds-jkreutzfeld requested changes

2023-02-17 09:07 UTC, ds-jkreutzfeld commented on charts/full-irs/Chart.yaml
> +    condition: install.irs.backend
It might be better to use the officially released IRS helm charts instead of copying it again.

2023-02-17 09:07 UTC, ds-jkreutzfeld commented on charts/full-irs/values.yaml
> +      url: &config-oauth-token-url "https://daps1.int.demo.catena-x.net/token"
Aren't you deploying your own DAPS server?

2023-02-17 09:08 UTC, ds-jkreutzfeld commented
Just FYI: As this kit uses the fraunhofer daps server, we cannot move it to eclipse due to legal issues.

2023-02-17 09:10 UTC, ds-jkreutzfeld commented
Also, please take a look at the Trivy security findings in this PR :)

2023-02-22 15:23 UTC, ds-jhartmann requested changes

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/edc-consumer-database-pv.yaml
> +    storage: 10Mi
10Mi is way to little capacity. I would recommend at least 100Mi for consumer

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/edc-consumer-database-pvc.yaml
> +      storage: 10Mi
10Mi is way to little capacity. I would recommend at least 100Mi for consumer

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/edc-provider-database-pv.yaml
> +    storage: 10Mi
I would recommend at least 500Mi for Provider

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/edc-provider-database-pvc.yaml
> +      storage: 10Mi
I would recommend at least 500Mi for Provider

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/irs-digital-twin-registry-database-pv.yaml
> +    storage: 10Mi
I would recommend at least 200Mi for Registry

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/irs-digital-twin-registry-database-pvc.yaml
> +      storage: 10Mi
I would recommend at least 200Mi for Registry

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/grafana-pv.yaml
> +    storage: 10Mi
I would recommend at least 500Mi for Grafana

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/grafana-pvc.yaml
> +      storage: 10Mi
I would recommend at least 500Mi for Grafana

2023-02-22 15:23 UTC, ds-jhartmann commented on charts/full-irs/templates/irs-digital-twin-registry-docker-secret.yaml
> +  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJaSE10YW1oaGNuUnRZVzV1T21kb2NGOU1aV1phTldnMlVqSlhVbVJJVW1Wa01YZ3lWRFZCZEhOVE4yOVZjV2N3ZG1zNFkzRT0ifX19
secret is still here!

2023-03-02 12:57 UTC, ds-jkreutzfeld approved these changes

2023-03-02 13:56 UTC, merged