TRI-1046: Created tests for investigation feature and several minor adjustments
catenax-ng/tx-item-relationship-service pull request #149
Opened 2023-02-17 12:53 UTC by ds-alexander-bulgakov

2023-02-17 15:35 UTC, ds-jkreutzfeld commented
Tests look good. Do we want to have this in main already? It should probably be merged to ess-dev at the moment, right?

2023-02-21 09:27 UTC, ds-alexander-bulgakov commented
> Tests look good. Do we want to have this in main already? It should probably be merged to ess-dev at the moment, right?

Actually i don´t know. Can´t we merge it to tx-irs since all tavern tests are in this project? What do you think @ds-jhartmann?

2023-02-21 09:53 UTC, ds-jhartmann commented
> > Tests look good. Do we want to have this in main already? It should probably be merged to ess-dev at the moment, right?
> 
> Actually i don´t know. Can´t we merge it to tx-irs since all tavern tests are in this project? What do you think @ds-jhartmann?

IMO we don't need scheduled tests for the supplychain feature. At least not until it is part of main. As Jan stated, we should add it to ess-dev. This way we can execute the Tavern tests on demand.

2023-02-21 09:53 UTC, ds-jhartmann requested changes

2023-02-21 09:53 UTC, ds-jhartmann commented on .github/workflows/tavern.yml
> +          IRS_ESS_HOST: ${{ github.event.inputs.irs-ess-host || 'https://irs-ess.dev.demo.catena-x.net' }}
Input `irs-ess-host` does not exist. You need to add this to the inputs for `workflow_dispatch` the same way as `irs-host`

2023-02-21 10:45 UTC, ds-alexander-bulgakov commented on .github/workflows/tavern.yml
> +          IRS_ESS_HOST: ${{ github.event.inputs.irs-ess-host || 'https://irs-ess.dev.demo.catena-x.net' }}
changed and commited.

2023-02-22 08:49 UTC, ds-alexander-bulgakov commented
I close this PR to avoid branch conflicts. New PR is created for ess-dev branch.

2023-02-22 08:49 UTC, closed without merging