feat(impl):[TRI-1145] verify bpn from token with the configured one, …
catenax-ng/tx-item-relationship-service pull request #192
Opened 2023-03-09 13:56 UTC by ds-ext-kmassalski

Verify bpn from token with the configured one before accessing API endpoint

2023-03-10 14:23 UTC, mkanal requested changes

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java
> +    @PreAuthorize("@authorizationService.verifyBpn() && hasAuthority('view_irs')")
I would change that to a method - bean direct in a annotation doesnt imrpove readability and is really hard to debug.

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java
> +    @PreAuthorize("@authorizationService.verifyBpn() && hasAuthority('view_irs')")
I would change that to a method - bean direct in a annotation doesnt imrpove readability and is really hard to debug.

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java
> +    @PreAuthorize("@authorizationService.verifyBpn() && hasAuthority('view_irs')")
I would change that to a method - bean direct in a annotation doesnt imrpove readability and is really hard to debug.

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java
> +    @PreAuthorize("@authorizationService.verifyBpn() && hasAuthority('view_irs')")
e.g.@PreAuthorize( isAuth() )

isAuth(){
 return @authorizationService.verifyBpn() && hasAuthority('view_irs')
}

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/AuthorizationService.java
> + * Verifies if token from JWT claim is equal to configured BPN
BPN contains in JWT Token matches BPN under which IRS product is registed.

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/SecurityHelperService.java
> +        return getClaimOrUnknown("clientId");
does mehtod return Unknown as String ??

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/SecurityHelperService.java
> +        return getClaimOrUnknown("bpn");
extract as constant

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/test/java/org/eclipse/tractusx/irs/services/AuthorizationServiceTest.java
> +    @Test
Empty or Unknown case sis that tested?

2023-03-10 14:23 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java
> +    @PreAuthorize("@authorizationService.verifyBpn() && hasAuthority('view_irs')")
same as above

2023-03-14 11:12 UTC, ds-jhartmann approved these changes
LGTM

2023-03-14 12:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java
> +    @PreAuthorize("@authorizationService.verifyBpn() && hasAuthority('view_irs')")
This is only pseudo code. I do not think that this is readable.

2023-03-14 13:26 UTC, mkanal approved these changes

2023-03-20 11:34 UTC, ds-jkreutzfeld submitted a review, later dismissed

2023-03-29 08:49 UTC, ds-jkreutzfeld approved these changes

2023-03-29 08:49 UTC, merged