Feature/tri 986 implement edc catalog caching
catenax-ng/tx-item-relationship-service pull request #213
Opened 2023-03-21 16:52 UTC by ds-jhartmann

2023-03-22 14:16 UTC, ds-jkreutzfeld requested changes

2023-03-22 14:16 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/CatalogCache.java
> +                                                                         o1.getValidUntil().toEpochMilli() - o2.getValidUntil().toEpochMilli()))
I think you can just use Instant.compareTo

2023-03-22 14:16 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/CatalogCache.java
> +            catalogItems.addAll(catalog.stream().map(this::updateTTL).toList());
What happens if the number of items in the catalog is larger than the cache size limit?

2023-03-22 14:16 UTC, ds-jkreutzfeld commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/EDCCatalogFacade.java
> +    public List<CatalogItem> getCatalog(final String connectorUrl, final String target) {
It's not clear to me from the method name that we are not retrieving the whole catalog, but instead all items of the catalog until we find a match.

2023-03-23 11:19 UTC, ds-jhartmann commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/CatalogCache.java
> +            catalogItems.addAll(catalog.stream().map(this::updateTTL).toList());
I changed the implementation to limit the max amount of at once cached items to the max configured cache size.

2023-03-23 11:19 UTC, ds-jhartmann commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/EDCCatalogFacade.java
> +    public List<CatalogItem> getCatalog(final String connectorUrl, final String target) {
Changed method name and added JavaDoc.

2023-03-23 11:19 UTC, ds-jhartmann commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/CatalogCache.java
> +                                                                         o1.getValidUntil().toEpochMilli() - o2.getValidUntil().toEpochMilli()))
Done

2023-03-23 11:20 UTC, ds-jhartmann commented on irs-api/src/main/java/org/eclipse/tractusx/irs/edc/CatalogCache.java
> +            return catalogItem.orElseThrow();
Done

2023-03-24 12:54 UTC, ds-jkreutzfeld submitted a review, later dismissed

2023-03-28 15:18 UTC, ds-jkreutzfeld approved these changes

2023-03-28 15:21 UTC, merged