feature/TRI-1197_tavern tests for batch-processing and boyscouting
catenax-ng/tx-item-relationship-service pull request #272
Opened 2023-04-18 07:40 UTC by ds-alexander-bulgakov

2023-04-18 09:15 UTC, ds-jhartmann requested changes

2023-04-18 09:15 UTC, ds-jhartmann commented on api-tests/testikus.tavern.yaml
Isn't this a duplicate of irs-api-tests.tavern.yaml?

2023-04-18 11:07 UTC, ds-alexander-bulgakov commented on api-tests/testikus.tavern.yaml
Yes, i removed the file. Please see next commit.

2023-04-20 10:58 UTC, ds-jhartmann approved these changes

2023-04-20 11:01 UTC, merged