Feature/TRI-1350 Update tavern tests to new aspects and testdataset
catenax-ng/tx-item-relationship-service pull request #404
Opened 2023-07-10 07:13 UTC by ds-alexander-bulgakov

2023-07-10 13:08 UTC, ds-jhartmann commented on .github/workflows/tavern.yml
> +          GLOBAL_ASSET_ID_AsBuild: ${{ github.event.inputs.global-asset-id-asBuild || 'urn:uuid:7940e0cc-7814-41eb-8b04-d984a325deec' }}
Please set the env vars as all caps e.g. GLOBAL_ASSET_ID_AS_PLANNED, GLOBAL_ASSET_ID_AS_BUILD

2023-07-10 13:08 UTC, ds-jhartmann commented on local/testing/api-tests/irs-api-tests.tavern.yaml
Please set the env vars as all caps e.g. GLOBAL_ASSET_ID_AS_PLANNED, GLOBAL_ASSET_ID_AS_BUILD

2023-07-10 15:09 UTC, ds-jhartmann requested changes

2023-07-10 15:09 UTC, ds-jhartmann commented on irs-load-tests/src/test/java/org/eclipse/tractusx/irs/IRSLoadTestSimulation.java
> +        headers_1.put("Authorization", "Bearer {access_token}");
Why was this changed?

2023-07-11 05:04 UTC, ds-alexander-bulgakov commented on irs-load-tests/src/test/java/org/eclipse/tractusx/irs/IRSLoadTestSimulation.java
> +        headers_1.put("Authorization", "Bearer {access_token}");
Probably accidentally. I corrected it!

2023-07-11 06:37 UTC, ds-jhartmann approved these changes

2023-07-11 06:39 UTC, merged