feat(impl):[TRI-1440] known knows
catenax-ng/tx-item-relationship-service pull request #413
Opened 2023-07-13 08:05 UTC by ds-ext-kmassalski

2023-07-13 08:46 UTC, ds-jhartmann requested changes

2023-07-13 08:46 UTC, ds-jhartmann commented on CHANGELOG.md
> +- High EDC resource demands - each EDC provider postgres uses > 2 CPU-Cores. The database storage gets filled after few days, until then, resource consumption increases. (EDC version: 0.4.1)
Since EDC 0.4.1 this is not an issue anymore

2023-07-13 09:08 UTC, ds-jhartmann commented on CHANGELOG.md
> +- High EDC resource demands - each EDC provider postgres uses > 2 CPU-Cores. The database storage gets filled after few days, until then, resource consumption increases. (EDC version: 0.4.1)
I already closed it

2023-07-13 14:09 UTC, ds-jkreutzfeld commented on CHANGELOG.md
Maybe we want to add that we are currently not really managing our resources (e.g. max threads)

2023-07-14 13:19 UTC, mkanal requested changes

2023-07-14 13:19 UTC, mkanal commented on CHANGELOG.md
> +- Lack of rate limiting of requests - IRS allows sending API requests in a massive, automated manner
```suggestion
- [TRI-1441] - No limiting of requests in paralle - IRS allows sending API requests unlimited
```

2023-07-14 13:19 UTC, mkanal commented on CHANGELOG.md
> +- Potential denial-of-service (DoS) attack - IRS allows to enter a large number of characters, which are reflected in the response of the server
Could you please more clear which parameter which ticket please?

2023-07-14 13:19 UTC, mkanal commented on CHANGELOG.md
> +- Software related information disclosure - IRS returns redundant information about the type and version of used software
What is this exactly? how to reproduce please add a ticket.

2023-07-17 15:26 UTC, ds-jhartmann requested changes

2023-07-17 15:26 UTC, ds-jhartmann commented on CHANGELOG.md
> +- [TRI-1455] Random 500 http status code returned by EDC during submodel retrievals. (EDC version: 0.4.1)
Not the case anymore with the latest IRS and EDC version

2023-07-19 09:18 UTC, mkanal requested changes

2023-07-19 09:18 UTC, mkanal commented on CHANGELOG.md
> +- Synchronous communication with external services without circuit breaker pattern - potentially could affect IRS resilience when other services becomes non-responsive
```suggestion
- [TRI-1441] Synchronous communication with shared C-X services without circuit breaker pattern - potentially could affect IRS resilience when other services becomes non-responsive.
```

2023-07-19 09:18 UTC, mkanal commented on CHANGELOG.md
> +- Cascading effects of failure when Digital Twin Registry becomes non-responsive - potentially bulkhead pattern could improve IRS resilience
```suggestion
- [TRI-1441] Cascading effects of failure when Digital Twin Registry becomes non-responsive - potentially bulkhead pattern could improve IRS resilience
```

2023-07-19 09:18 UTC, mkanal commented on CHANGELOG.md
> +- Retry mechanism used inside IRS could potentially affect IRS resilience - DDOS other services on which IRS is dependent, exhaustion of resources and available threads, etc.
```suggestion
- [TRI-1477] Retry mechanism used inside IRS could potentially affect IRS resilience - DDOS other services on which IRS is dependent, exhaustion of resources and available threads, etc.
```

2023-07-19 09:18 UTC, mkanal commented on CHANGELOG.md
> +- Lack of resources management - max threads, heap limitation, etc.
```suggestion
- [TRI-1478] Lack of resources management - thread pooling, heap limitation etc.
```

2023-07-19 09:18 UTC, mkanal commented on CHANGELOG.md
> +- IRS was not scaled to multiple instances, and was not tested in such environment
```suggestion
- [TRI-1024] IRS does not support scale out on multiple instances
```

2023-07-19 09:19 UTC, mkanal approved these changes

2023-07-19 10:34 UTC, ds-jhartmann approved these changes

2023-07-19 10:40 UTC, ds-jkreutzfeld approved these changes

2023-07-19 11:22 UTC, merged