feat(impl):[TRI-1093] base implementation of data integrity
catenax-ng/tx-item-relationship-service pull request #469
Opened 2023-08-03 13:47 UTC by ds-ext-kmassalski

- always store Relationship submodel
- add delegate that stores DataIntegrity aspects
- before completing job - validate chain data integrity

2023-08-07 15:28 UTC, ds-jhartmann commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +    private boolean submodelDataIntegrityIsValid(final Submodel submodel, final Set<IntegrityAspect> integrities) {
Signature validation is missing.

2023-08-07 15:28 UTC, ds-jhartmann commented on irs-api/src/main/java/org/eclipse/tractusx/irs/connector/job/BaseJobStore.java
> +                return job.toBuilder().transitionComplete(dataIntegrityService.chainDataIntegrityIsValid(itemContainer)).build();
Wouldn't it be more fitting to verify integrity in JobOrchestrator or AASRecursiveJobHandler instead of JobStore? 
I would not associate validation tasks with storage.

2023-08-14 09:25 UTC, mkanal requested changes

2023-08-14 09:25 UTC, mkanal commented on docs/src/api/irs-v1.0.yaml
> +        integrityChainValid: false
integrityState

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/IntegrityAspect.java
> +    private Set<ChildData> childParts;
Why Set<ChildData> and not <ChildParts>? Is Set the correct collection type to use as there might be multiple childParts with the same ID inside a SingleLevelB?

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/IntegrityDelegate.java
> +    private static final String DATA_INTEGRITY_ASPECT = "DataIntegrity";
Why is the constant private?  In this case we need multiple constants pointing to the same information. As it is a constant the aspect should be available in the same colleciton as all other aspects as well.

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/IntegrityDelegate.java
> +            log.info("Submodel payload did not match the expected AspectType. Creating Tombstone.");
I recommend to use .error or .warn not .info

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/IntegrityDelegate.java
> +            log.info("Submodel Endpoint could not be retrieved for Endpoint: {}. Creating Tombstone.",
Recommendation to use .error or .warn not .info

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/connector/job/BaseJobStore.java
> +                final boolean chainDataIntegrityIsValid =
dataChainIntegrity = integrity is true or false adding isvalid duplicates the information already given be integrity. integrity is already positively evidenced

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +            messageDigest = MessageDigest.getInstance("SHA3-256");
Please update concept and ticket in case using SHA3-256. In addition no magic strings.

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +            log.error("Cannot create public key object based on injected publicKeyCert data", e);
add important subjectPublicKeyInfo information to log message to provide more infos how to fix this situation.

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +        final long numberOfValidSubmodels = itemContainer.getSubmodels().stream().takeWhile(submodel -> {
integerSubmodels = Validation is made with schema validation - we check if these submodels are integer - that does not indicates that the payloads are valid or not. Even invalid payloads could be integer.

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +                log.error("Validation of data integrity not possible - DataIntegrity aspect is missing");
```suggestion
                log.error("DataIntegrity aspect is missing. Integrity of data chain cannot be determined.");
```

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +        return numberOfValidSubmodels == totalNumberOfSubmodels(itemContainer);
```suggestion
        return numberOfIntegerSubmodels == totalNumberOfSubmodels(itemContainer);
```

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +        log.debug("Comparing hashes and signatures Data integrity of Submodel {}", submodel.getIdentification());
```suggestion
        log.debug("Comparing hashes and signatures Data integrity of Submodel id: {}", submodel.getIdentification());
```

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +        return hashesAreEqual(reference.getHash(), calculatedHash)
-
```suggestion
        return hashesEquals(reference.getHash(), calculatedHash)
```

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +    private static boolean hashesAreEqual(final String hashReference, final String calculatedHash) {
```suggestion
    private static boolean hashesEquals(final String hashReference, final String calculatedHash) {
```

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/main/java/org/eclipse/tractusx/irs/services/DataIntegrityService.java
> +    private boolean signaturesAreEqual(final String signatureReference, final byte[] hashedMessage) {
```suggestion
    private boolean signaturesEquals(final String signatureReference, final byte[] hashedMessage) {
```

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/IntegrityDelegateTest.java
> +                                                                                                       "DataIntegrity",
use contant not magic strings

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/IntegrityDelegateTest.java
> +                                                                                                       "DataIntegrity",
use contant not magic strings

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/SubmodelDelegateTest.java
> +                "itemId");
use contant not magic strings

2023-08-14 09:25 UTC, mkanal commented on irs-api/src/test/java/org/eclipse/tractusx/irs/services/DataIntegrityServiceTest.java
> +        dataIntegrityService = new DataIntegrityService(publicKey);
Recommendation is to use BigInteger instead of String using the correct encoding Base64.decodeBase64

2023-08-14 14:06 UTC, mkanal submitted a review, later dismissed

2023-09-01 11:39 UTC, ds-jhartmann approved these changes

2023-09-01 11:42 UTC, merged