Tri 1417 ess bottom up approach
catenax-ng/tx-item-relationship-service pull request #559
Opened 2023-09-28 16:22 UTC by mkanal

- add concept artefacts for ess bottom up approach

2023-09-29 09:44 UTC, ds-jhartmann requested changes

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/activity/1_incident_scenario_ess-bottom_up-activity.puml
> +if(aas.isEmpty?) then (no)
```suggestion
if(aas.isEmpty?) then (yes)
```

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/activity/1_incident_scenario_ess-bottom_up-activity.puml
> +if(twinsAsPlanned.isEmpty?) then (no)
```suggestion
if(twinsAsPlanned.isEmpty?) then (yes)
```

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/activity/1_incident_scenario_ess-bottom_up-activity.puml
> +if(!twin.contains(incidentBpns)) then (no)
why the negation? This makes it really hard to read

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/activity/1_incident_scenario_ess-bottom_up-activity.puml
> +if(PartAsPlanned.validityPeriod.validFrom
Make this more readable by just saying: Timestamp is in PartAsPlanned validity period

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/sequence/ess-bottom-up-sequence-customer-highlevel.puml
> +        "incidentBpn" : ["BPNS123456"]
```suggestion
        "incidentBPNSs" : ["BPNS123456"]
```

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/sequence/ess-bottom-up-sequence-customer-highlevel.puml
> +            ]
Why is this an array? A GlobalAssetId should only be linked to one company, right?

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/sequence/ess-bottom-up-sequence-originator-highlevel.puml
> +            incidentBpns [<bpns>,..],
```suggestion
            incidentBPNSs [<bpns>,..],
```

2023-09-29 09:44 UTC, ds-jhartmann commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/sequence/ess-bottom-up-sequence-originator-highlevel.puml
> +                     ]
Not sure about this very generic parameter. This gives a wrong indication of "choose yourself what you want to filter" which is not the case, since the actual implementation is dependent on the aspects which the ESS investigation service requests and the underlying business logic which does the validation

2023-10-16 09:31 UTC, mkanal commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/sequence/ess-bottom-up-sequence-customer-highlevel.puml
> +            ]
This is a bpns and not a bpnl - globalAssetId could be related to multiple bpns.

2023-10-16 09:34 UTC, mkanal commented on docs/src/uml-diagrams/irs-recursive/ess-bottom-up/sequence/ess-bottom-up-sequence-originator-highlevel.puml
> +                     ]
I think we have to describe that we have inbuilt filter expressions to be set. I need a structure which is extendable. As we have currently no generic filter mechanism in IRS we have to add inbuilt filter expressions like that.

2023-10-19 06:38 UTC, ds-jhartmann approved these changes

2023-10-27 13:17 UTC, merged