feat(docs):[TRI-1604] Add concept for EDR caching and reuse
catenax-ng/tx-item-relationship-service pull request #581
Opened 2023-10-10 15:13 UTC by ds-jhartmann

2023-10-11 10:40 UTC, mkanal requested changes

2023-10-11 10:40 UTC, mkanal commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +# [Concept] EDC EDR Token negotiation and usage
Please add the JIRA-ID as a reference in filename and Please add a meta header section containing the information author and JIRA-ID , Creation date,   Due Date, author Confidentiality level:

2023-10-11 10:40 UTC, mkanal commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +1. IRS has to check first, if an EDR Token for the requested EDC Asset ID is available in EDR-Storage
```suggestion
1. IRS has to check first, if an EDR Token for the requested EDC Asset ID is available in EndpointDataReferenceStorage (EDR-Storage)
```

2023-10-11 10:40 UTC, mkanal commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +# [Concept] EDC EDR Token negotiation and usage
```suggestion
# Glossar
| Abbreviation| Name | 
| EDR-Storage |EndpointDataReferenceStorage| 
| EDR|EndpointDataReference| 


# [Concept] EDC EDR Token negotiation and usage
```

2023-10-11 10:40 UTC, mkanal commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +    D --> E{isExpired}
Add case If expiry date is not available.
Add case if expiry date is not valid ?

2023-10-11 11:06 UTC, ds-jhartmann commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +# [Concept] EDC EDR Token negotiation and usage
Added only the Jira ID, as discussed.

2023-10-11 11:06 UTC, ds-jhartmann commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +1. IRS has to check first, if an EDR Token for the requested EDC Asset ID is available in EDR-Storage
Added this to one section above

2023-10-11 11:07 UTC, ds-jhartmann commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +# [Concept] EDC EDR Token negotiation and usage
Done with correct format

2023-10-11 11:07 UTC, ds-jhartmann commented on docs/concept/EDR-Token-Cache-and-reuse.md
> +    D --> E{isExpired}
done

2023-10-12 05:42 UTC, mkanal approved these changes

2023-10-12 07:44 UTC, jzbmw approved these changes
looks reasonable. 👍

2023-10-12 07:45 UTC, jzbmw commented
I would like to discuss the dependencies to policies.

2023-10-12 09:00 UTC, merged