feat:[TRI-1685]: added example values to open api yaml, fixed problem…
catenax-ng/tx-item-relationship-service pull request #603
Opened 2023-10-23 11:08 UTC by ds-psosnowski

## Description
Added example values to open-api documentation and also did some clean up.
**Note:** Instead of using OpenApiExamples class I had to use direct examples in Schema annotation, since Open Api did not generate it correctly.  

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-10-23 12:42 UTC, ds-jhartmann requested changes

2023-10-23 12:42 UTC, ds-jhartmann commented on irs-models/src/main/java/org/eclipse/tractusx/irs/component/assetadministrationshell/ProtocolInformation.java
> +    @Schema(implementation = String.class, example = "https://catena-x.net/vehicle/basedetails")
I recommend to use an example value for href similar to https://eclipse-tractusx.github.io/docs-kits/kits/Traceability%20Kit/Software%20Development%20View/Specification%20Traceability%20Kit#submodel-descriptors

2023-10-23 12:42 UTC, ds-jhartmann commented on irs-models/src/main/java/org/eclipse/tractusx/irs/component/Relationship.java
> +    @Schema(implementation = String.class, example = "supply_chain_impacted")
Example for a Relationship aspectType would be "SingleLevelBomAsBuilt".

2023-10-23 13:48 UTC, ds-jhartmann commented on irs-models/src/main/java/org/eclipse/tractusx/irs/component/assetadministrationshell/ProtocolInformation.java
> +    @Schema(implementation = String.class, example = "https://catena-x.net/vehicle/basedetails")
Sorry for the confusion, I meant the example found on this site 😄 
"href": "https://edc.data.plane/{path}/submodel"

2023-10-23 17:03 UTC, ds-psosnowski commented on irs-models/src/main/java/org/eclipse/tractusx/irs/component/assetadministrationshell/ProtocolInformation.java
> +    @Schema(implementation = String.class, example = "https://catena-x.net/vehicle/basedetails")
oh sorry, I've just copied it 😄 fixing it right away

2023-10-24 06:37 UTC, ds-jhartmann approved these changes

2023-10-24 07:43 UTC, merged