feat(irs-api):[#244] Fixed chron duration to be in ISO format, added …
catenax-ng/tx-item-relationship-service pull request #636
Opened 2023-11-14 14:12 UTC by ds-psosnowski

Changed chron to use ISO format
Adjusted commit-msg format to match github style

2023-11-14 14:28 UTC, ds-jhartmann requested changes

2023-11-14 14:28 UTC, ds-jhartmann commented on CHANGELOG.md
> +- Updated commit message format check to match github pattern
That's not product related and does not need to be part of the changelog

2023-11-14 14:28 UTC, ds-jhartmann commented on charts/irs-helm/values.yaml
> +    cacheTTL: PT24H # Time to live for ConnectorEndpointService for fetchConnectorEndpoints method cache
Comments need to be separated by two spaces
```suggestion
    cacheTTL: PT24H  # Time to live for ConnectorEndpointService for fetchConnectorEndpoints method cache
```

2023-11-14 14:28 UTC, ds-jhartmann commented on irs-api/src/main/resources/application.yml
> +    cacheTTL: PT24H
Please also add a description what this parameter does (can be the same as for values.yaml)

2023-11-14 14:32 UTC, ds-jhartmann commented on irs-api/src/main/resources/application.yml
> +    cacheTTL: PT24H
Is `@Scheduled` able to use a ISO 8601 format?

2023-11-14 14:36 UTC, ds-psosnowski commented on irs-api/src/main/resources/application.yml
> +    cacheTTL: PT24H
Yes it is, we use it in other places, also I've checked the documentation.
Will add comment.

2023-11-14 14:52 UTC, ds-jhartmann approved these changes
LGTM

2023-11-14 14:53 UTC, ds-jhartmann commented
Chart linting is failing, please fix

2023-11-16 15:36 UTC, ds-psosnowski commented on local/development/commit-msg
> +if ! echo "$commitTitle" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\([a-z0-9/-]+\)\:\[#[0-9]+\].*$'; then
ticket number is not set to optional, any regex that I've tried that works in regex check doesn't work in bash for some reason

2023-11-17 11:31 UTC, ds-jhartmann commented on local/development/commit-msg
> +if ! echo "$commitTitle" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\([a-z0-9/-]+\)\:\[#[0-9]+\].*$'; then
This regex should work
```suggestion
if ! echo "$commitTitle" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\([a-z0-9/-]+\)\:(\[#[0-9]+\])?.*$'; then
```

2023-11-17 11:46 UTC, ds-psosnowski commented on local/development/commit-msg
> +if ! echo "$commitTitle" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\([a-z0-9/-]+\)\:\[#[0-9]+\].*$'; then
yea I've tested it, it works as regex but for some reason bash return it as error

2023-11-17 13:22 UTC, ds-jhartmann commented on local/development/commit-msg
> +if ! echo "$commitTitle" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\([a-z0-9/-]+\)\:\[#[0-9]+\].*$'; then
I tested this with the git hook and it is working

2023-11-17 13:35 UTC, ds-jhartmann approved these changes

2023-11-17 13:35 UTC, ds-jhartmann commented on local/development/commit-msg
> +if ! echo "$commitTitle" | grep -qE '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\([a-z0-9/-]+\)\:\[#[0-9]+\].*$'; then
Alright, lets leave it for now.

2023-11-17 13:51 UTC, ds-jhartmann approved these changes

2023-11-17 14:03 UTC, merged