chore(concept): rename propery from alternative to hasAlternatives
catenax-ng/tx-item-relationship-service pull request #662
Opened 2023-11-22 11:41 UTC by mkanal

chore(concept): rename propery from alternative to hasAlternatives

2023-11-22 12:06 UTC, ds-jhartmann requested changes

2023-11-22 12:06 UTC, ds-jhartmann commented on docs/concept/#212-Update-of-aspect-model-SingleLevelBomAsBuilt-2_0_0/#212-Update-SingleLevelBomAsBuilt-2-0-0.md
> +    s5 --> SerialPart4(SingleLevelBomAsBuilt2.0.0)
name mismatch: SerialPart or SingleLevelBomAsBuilt2.0.0 ?

2023-11-22 16:34 UTC, mkanal commented on docs/concept/#212-Update-of-aspect-model-SingleLevelBomAsBuilt-2_0_0/#212-Update-SingleLevelBomAsBuilt-2-0-0.md
> +    s5 --> SerialPart4(SingleLevelBomAsBuilt2.0.0)
```suggestion
    s5 --> SingleLevelBomAsBuilt4(SingleLevelBomAsBuilt2.0.0)
```

2023-11-22 16:34 UTC, mkanal commented on docs/concept/#212-Update-of-aspect-model-SingleLevelBomAsBuilt-2_0_0/#212-Update-SingleLevelBomAsBuilt-2-0-0.md
> +   s4 --> SerialPart5(SingleLevelBomAsBuilt2.0.0)
```suggestion
   s4 --> SingleLevelBomAsBuilt5(SingleLevelBomAsBuilt2.0.0)
```

2023-11-23 07:42 UTC, ds-jhartmann approved these changes
LGTM

2023-11-23 07:45 UTC, merged