fix(diagram):[#212] adjust diagram
catenax-ng/tx-item-relationship-service pull request #666
Opened 2023-11-24 14:04 UTC by mkanal

fix(diagram):[#212] adjust diagram

2023-11-27 08:07 UTC, ds-psosnowski approved these changes

2023-11-28 10:25 UTC, ds-jhartmann requested changes

2023-11-28 10:25 UTC, ds-jhartmann commented on docs/concept/#212-Update-of-aspect-model-SingleLevelBomAsBuilt-2_0_0/#212-Update-SingleLevelBomAsBuilt-2-0-0.md
> +    s3 --> SerialPart5(Batch)
```suggestion
    s2 --> Batch1(Batch)
    s3 --> Batch2(Batch)
```

2023-11-28 10:36 UTC, ds-jhartmann approved these changes

2023-12-06 11:34 UTC, merged