Feature/#206 update ess documentation
catenax-ng/tx-item-relationship-service pull request #669
Opened 2023-11-28 08:55 UTC by ds-jhartmann

2023-11-29 13:33 UTC, ds-jhartmann commented on README.md
> +the IDE.
In Markdown, new lines are not rendered unless you have two breaks or add two spaces at the end of the line. 
I just formatted the whole file and it added line breaks on long lines. If you take a look at the rich diff, you can see that these lines did not change.

2023-12-04 09:12 UTC, ds-psosnowski submitted a review, later dismissed
LGTM

2023-12-04 15:09 UTC, mkanal requested changes

2023-12-04 15:09 UTC, mkanal commented on docs/src/docs/index.adoc
> +This work is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0].
Is this correct, I assume [Apache2.0](https:) ??

2023-12-04 15:09 UTC, mkanal commented on docs/src/uml-diagrams/deployment-view/level-0-dev.puml
> +    component "Digital Twin Registry" as dtr
```suggestion
    component "Decentral Digital Twin Registry" as dtr
```

2023-12-04 15:37 UTC, ds-jhartmann commented on docs/src/docs/index.adoc
> +This work is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0].
Yes, this is correct. Links in AsciiDoc are different from links in markdown. Markdown syntax is `[Display Text](url)`, AsciiDoc syntax is `url[Display Text]`

2023-12-05 09:46 UTC, ds-jhartmann commented on DataChainKit.md
>  ### Requirements
Since this is not part of the story I would like to move this discussion to a later time so I can merge this PR and close the story

2023-12-05 09:47 UTC, mkanal submitted a review, later dismissed

2023-12-05 12:41 UTC, merged