feat(irs-apiirs-edc-client):[#256] added cache mechanism for edr tokens
catenax-ng/tx-item-relationship-service pull request #679
Opened 2023-12-01 14:16 UTC by ds-psosnowski

2023-12-04 10:12 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/ContractNegotiationService.java
> +                        contractAgreementId);
I don't think this is sensitive information, but please confirm

2023-12-05 10:10 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/ContractNegotiationService.java
> +                        Masker.mask(contractAgreementId));
value masked

2023-12-06 14:43 UTC, ds-jhartmann requested changes

2023-12-06 14:43 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EndpointDataReferenceStorage.java
> +                storageMap.get(storageId) != null ? storageMap.get(storageId).getDataReference() : null);
Instead of setting the null value manually, please retrieve the EDR from the storage map in the same manner as in the "remove" method

2023-12-06 14:43 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcSubmodelClient.java
>          return endpointDataReferenceStorage.remove(contractAgreementId);
EDR caching will not work because the EDR is removed from the cache when it is retrieved here. Please switch to `endpointDataReferenceStorage.get()` instead of `endpointDataReferenceStorage.remove()`

2023-12-06 14:43 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/ContractNegotiationService.java
> +        String contractAgreementId = null;
redundant initialize

2023-12-06 14:43 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/ContractNegotiationService.java
> +        NegotiationResponse negotiationResponse = null;
negotiationResponse is set to null and can be returned as null, if I understand this right. This might be a potential NullpointerException in case of a expired EDR token because the returned negotiation response will be used later on to get the contractAgreementId

2023-12-06 14:43 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/ContractNegotiationService.java
> +    @SuppressWarnings("PMD.AvoidReassigningParameters")
I would prefer to actually assign the parameter to a variable and leaving the parameter as final. Suppressing warnings should only be used if absolutely necessary

2023-12-06 14:43 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcSubmodelClient.java
> +    @SuppressWarnings("PMD.ConfusingTernary")
Please avoid to use SuppressWarnings if possible. You can do this here by assigning `cachedEndpointDataReference.tokenStatus() != TokenStatus.VALID` to a variable with a descriptive name

2023-12-06 15:14 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcSubmodelClient.java
> +        final Optional<EndpointDataReference> dataReference = retrieveEndpointDataReferenceByContractAgreementId(
caching the EDR Token here is too late, since the Negotiation has already been started in  `EdcSubmodelClientImpl#sendNotification`

2023-12-07 12:11 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/ContractNegotiationService.java
> +        NegotiationResponse negotiationResponse = null;
that is really good point, I've missed it somehow, while token is expired it should use assetId not contractAgreementId and it would produce NP

2023-12-07 13:30 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcSubmodelClient.java
> +        final Optional<EndpointDataReference> dataReference = retrieveEndpointDataReferenceByContractAgreementId(
This flow will go with always reqire_new token status, do we want also to include caching here?

2023-12-12 14:10 UTC, ds-jhartmann requested changes

2023-12-13 08:21 UTC, ds-psosnowski commented on irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/SubmodelRetryerTest.java
> +        verify(restTemplate, times(retryRegistry.getDefaultConfig().getMaxAttempts() * 3)).exchange(any(String.class),
I completely misunderstood the test, I though new code is being called 3 times each, after investigation it turned out it is called 3 times because there is `execute()` method called inside another `execute()`. 
Test can be reworked or just be more descriptive but I'm double-checking if calling one method in another is not a problem or it should be designed differently.

2023-12-21 11:58 UTC, ds-jhartmann approved these changes
LGTM. Great Work!

2024-01-08 09:09 UTC, merged