Feat(impl)/225 use caching for discovery finder requests
catenax-ng/tx-item-relationship-service pull request #693
Opened 2023-12-08 23:31 UTC by dsmf

2023-12-09 01:19 UTC, dsmf commented
https://github.com/eclipse-tractusx/item-relationship-service/issues/225

2023-12-11 11:47 UTC, ds-jhartmann requested changes
Some minor changes requested. Everything else looks good!

2023-12-11 14:22 UTC, ds-psosnowski submitted a review, later dismissed

2023-12-11 14:22 UTC, ds-psosnowski commented on irs-api/src/test/java/org/eclipse/tractusx/irs/DiscoveryFinderClientTest.java
> +        {
btw. what is the point of scoping with `{}`?

2023-12-12 09:52 UTC, dsmf commented on irs-api/src/test/java/org/eclipse/tractusx/irs/DiscoveryFinderClientTest.java
> +        {
Technically none. But I use this in tests sometimes in order to group a block of asserts that belong together. This way it is sufficient for the reader to read only the comment above the {} block to understand what the test is about to assert. In real production code I'd rather use extract-to-method here, but in test I find it more helpful this way (unless the same asserts are used in other tests).

2023-12-12 16:32 UTC, ds-jhartmann reviewed
Some minor grammatical suggestions

2023-12-12 16:32 UTC, ds-jhartmann commented on docs/src/docs/administration/configuration.adoc
> +When IRS calls the DTR discovery finder URL for BPNL's there is a cache mechanism between them, to improve performance.
```suggestion
When IRS calls the Discovery Finder URL for BPNLs, the results are cached to improve performance.
```

2023-12-12 16:32 UTC, ds-jhartmann commented on docs/src/docs/administration/configuration.adoc
> +When IRS calls EDC Discovery Service to fetch connector endpoints for BPNL's there is a cache mechanism between them, to improve performance.
```suggestion
When IRS calls EDC Discovery Service to fetch connector endpoints for BPNLs, the results are cached to improve performance.
```

2023-12-12 16:32 UTC, ds-jhartmann commented on docs/src/docs/arc42/cross-cutting/under-the-hood.adoc
> +Please find more information on Discovery Service see chapter "System scope and context".
```suggestion
Further information on Discovery Service can be found in the chapter "System scope and context".
```

2023-12-12 17:42 UTC, dsmf commented on docs/src/docs/arc42/cross-cutting/under-the-hood.adoc
> +Please find more information on Discovery Service see chapter "System scope and context".
Hi @ds-jhartmann , 

Ah yes, the "see" was a mistake. Completely overlooked that when I rewrote the sentence. 

However the term "Please find more information" is a correct formal term AFAIK:  https://www.linguee.de/englisch-deutsch/uebersetzung/please+find+more+information.html

To keep things short I'll just use your suggestion.

2023-12-13 07:23 UTC, ds-jhartmann approved these changes

2023-12-13 11:41 UTC, merged