Chore/#322 provisioning of contract negotiation and contract assessment for assets
catenax-ng/tx-item-relationship-service pull request #724
Opened 2024-01-18 13:40 UTC by mkanal

Provisioning of required identifications for contract negation and contract agreement id edc:ContractAgreementDto@id
 IRS provides the ContractAgreeementId for data asset in JobResponse on demand
 How the business app can request the edc:ContractAgreement and ContractNegotation Payload to visualize the required results
 Specify the time period the ContractAgreeementId payload and ContractNegotation payload should be accessible and be available for the business app - according to that decide if information should be stored in IRS or stored in the EDC. How long does the EDC store this information and is it sufficient to store this in the EDC - (10 years according to law)

2024-01-19 11:14 UTC, ds-jhartmann requested changes

2024-01-19 11:14 UTC, ds-jhartmann commented on docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md
> +## 3. Case 3: IRS proceed successful EDC contract negotiation and revokes asset transfers cause by not matching usage policy
Usage policy is checked before contract negotiation. In case of invalid policy, no negotiation will be started.

2024-01-19 11:14 UTC, ds-jhartmann commented on docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md
> +````mermaid
Diagram does not match case 3

2024-01-19 11:14 UTC, ds-jhartmann commented on docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md
> +
Duplicate
```suggestion
```

2024-01-19 11:14 UTC, ds-jhartmann commented on docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md
> +### <ins>Add Tombstone in case of not matching policy</ins>
I would strongly recommend to add the invalid policy to the `processingError` object as part of `errorDetails`. 
Adding fields to tombstone based on certain flags which can be toggled via API param is messy.

2024-01-19 11:14 UTC, ds-jhartmann commented on docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md
> +          "errorDetail": "EndpointDataReference was not found. Requested connectorEndpoints: https://dsi-int-2-1llhjasi.c-5e7e41f.stage.kyma.ondemand.com, https://sap-3-2-ap-edc1-cp.foss.cx.shoot.liv
please use dummy URLs here

2024-01-19 11:14 UTC, ds-jhartmann commented on docs/concept/TEMPLATE_Concept.md
HTML Tags in Markdown is not a good practice. Refer to comments in docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md

2024-01-19 15:23 UTC, mkanal commented on docs/concept/#322-Provisioning-of-contract-definiton-for-assets/#322-Provisioning-of-contract-definiton-for-assets.md
> +          "errorDetail": "EndpointDataReference was not found. Requested connectorEndpoints: https://dsi-int-2-1llhjasi.c-5e7e41f.stage.kyma.ondemand.com, https://sap-3-2-ap-edc1-cp.foss.cx.shoot.liv
```suggestion
          "errorDetail": "EndpointDataReference was not found. Requested connectorEndpoints: https://test.doubleSlash.com, https://test2.doubleSlash.com",
```

2024-01-22 13:11 UTC, ds-jhartmann approved these changes
LGTM

2024-01-22 13:11 UTC, merged