Feature/412 irs lib asset policy and contract creation services added
catenax-ng/tx-item-relationship-service pull request #753
Opened 2024-02-01 12:51 UTC by ds-ext-sceronik

2024-02-02 11:07 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/policy/service/EdcPolicyDefinitionService.java
> +                                                                                                                  new EdcOperator(
take a look at `org.eclipse.tractusx.irs.edc.client.policy` package, there are already classes for constraints, maybe you could reuse them instead of adding new? :) 
example `org.eclipse.tractusx.irs.edc.client.policy.OperatorType`

2024-02-02 11:07 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/model/AssetRequest.java
> +public class AssetRequest {
how about `record` for pojo's?

2024-02-05 11:40 UTC, ds-jhartmann requested changes

2024-02-05 11:40 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractDefinitionService.java
> +    private static final String CONTRACT_DEFINITION_PATH = "/management/v2/contractdefinitions";
Please make this path configurable

2024-02-05 11:40 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java
> +            final RestTemplate restTemplate) {
I would prefer to have the RestTemplate passed via dependency injection rahter than passed as parameter of the method. 
This would better algin with our code style

2024-02-05 11:46 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/model/exception/CreateEdcAssetException.java
Please consider, if checked exceptions suit this better. 
If you want to keep the RuntimeException, please add a reference to the JavaDoc of the public methods, where the exceptions can occur

2024-02-05 12:10 UTC, ds-ext-sceronik commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java
> +            final RestTemplate restTemplate) {
Yes I am aware of that . although we would need to provide multiple restTemplates with different edc configurations. ( we are currently supporting 2 EDCs ) with different keys and host paths. 
that is why I went with this approach untill we actually have 1 single EDC for notifications and data providing.

2024-02-05 12:31 UTC, ds-ext-sceronik commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/EDRAuthCode.java
removed as not needed did not notice I do not use it in requests . if in future we will need it I will make sure to use provided one :)

2024-02-06 09:55 UTC, ds-ext-sceronik commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java
> +            final RestTemplate restTemplate) {
changed usage approach of services . now need to create beans from services with preconfigured restTemplates :)

2024-02-19 08:18 UTC, ds-jhartmann requested changes

2024-02-19 08:18 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java
> +                                                                   "https://w3id.org/edc/v0.0.1/ns/dataAddress/method",
Please use constants for this. See `irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/transformer/EdcTransformer.java`

2024-02-19 08:18 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/transformer/EdcTransformer.java
> +                "https://w3id.org/edc/v0.0.1/ns/dataAddress/proxyQueryParams");
Please use constants for this. See `irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetService.java`

2024-02-19 08:40 UTC, ds-jhartmann commented on CHANGELOG.md
CHANGELOG has conflicts. Please move your added changes to the Unreleased section

2024-02-19 17:35 UTC, ds-jhartmann commented on irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetServiceTest.java
> +                	},
Properties are not transformed correctly

2024-02-19 18:35 UTC, ds-ext-sceronik commented on irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetServiceTest.java
> +                	},
this is 1to1 mapping as we created notifiaction assets on our system . and it worked. how it supposed to be transformed ?

2024-02-20 07:57 UTC, ds-jhartmann commented on irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/asset/EdcAssetServiceTest.java
> +                	},
In this test you set some properties for the Asset: `
```
Map<String, Object> properties = Map.of("description", "endpoint to qualityinvestigation receive",
                "contenttype", "application/json", "policy-id", "use-eu", "type", "receive", "notificationtype",
                "qualityinvestigation", "notificationmethod", "receive");
```
These properties are not added to the properties of the asset

2024-02-20 08:02 UTC, ds-jhartmann approved these changes
Besides the asset properties, this looks good to me. 
If you want, you can fix that, if not, you can merge. Either ways works fine for me

2024-02-20 08:08 UTC, merged