Sync with upstream
catenax-ng/tx-item-relationship-service pull request #785
Opened 2024-02-22 15:43 UTC by ds-jhartmann

2024-02-23 11:03 UTC, dsmf requested changes

2024-02-23 11:03 UTC, dsmf commented on CHANGELOG.md
>  [4.6.0]: https://github.com/eclipse-tractusx/item-relationship-service/compare/4.5.1...4.6.0
```suggestion
[4.6.0]: https://github.com/eclipse-tractusx/item-relationship-service/compare/4.5.2...4.6.0
```

2024-02-23 11:47 UTC, ds-jhartmann commented on CHANGELOG.md
>  [4.6.0]: https://github.com/eclipse-tractusx/item-relationship-service/compare/4.5.1...4.6.0
Thanks for the hint, but I cannot commit this suggestion since this PR is from main to main

2024-02-26 14:06 UTC, dsmf approved these changes

2024-02-26 14:07 UTC, merged