feature: 420 add /management/v2/contractagreements/request and GET  /…
catenax-ng/tx-item-relationship-service pull request #787
Opened 2024-02-26 08:26 UTC by ds-lcapellino

…management/v2/contractagreements/{contractAgreementId}/negotiation to irs-edc-client lib

2024-02-26 15:10 UTC, ds-jhartmann requested changes
Some minor refactoring suggestions, everything else looks good :)

2024-02-26 15:10 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/model/exception/ContractAgreementException.java
> +public class ContractAgreementException extends RuntimeException {
We usually use checked Exceptions for this. See e.g. EdcClientException, TransferProcessException.
If possible, please align with that.

2024-02-26 15:10 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/contract/service/EdcContractAgreementService.java
> +                                                                                        "https://w3id.org/edc/v0.0.1/ns/assetId")
Pleas add `"https://w3id.org/edc/v0.0.1/ns/assetId"` as constant

2024-02-26 15:36 UTC, ds-jhartmann requested changes

2024-02-26 15:36 UTC, ds-jhartmann commented on charts/irs-helm/values.yaml
> +      contractAgreements: /management/v2/contractagreements # EDC consumer controlplane contract agreements path
We have templated the `controlplane.endpoint.data` field to `"http://%s%s" .Release.Name "-tractusx-connector-controlplane:8081/management"` by default, so the `/management` path is included there already.
The name "data" might be a bit misleading here.

2024-02-26 15:39 UTC, ds-jhartmann commented on charts/irs-helm/values.yaml
> +      contractAgreements: /management/v2/contractagreements # EDC consumer controlplane contract agreements path
```suggestion
      contractAgreements: /management/v2/contractagreements  # EDC consumer controlplane contract agreements path
```

2024-02-27 07:40 UTC, ds-lcapellino commented
Thanks for the feedback @ds-jhartmann. Please see the new changes :)

2024-02-27 07:59 UTC, ds-jhartmann approved these changes
LGTM

2024-02-28 07:10 UTC, merged