feat(irs-api):[#199] register policy definition for certain bpnls
catenax-ng/tx-item-relationship-service pull request #802
Opened 2024-03-05 14:26 UTC by ds-psosnowski

2024-03-07 08:59 UTC, dsmf requested changes
Hi @ds-psosnowski, please add CHANGELOG entry including GitHub issue id

2024-03-12 16:21 UTC, ds-jhartmann requested changes

2024-03-12 16:21 UTC, ds-jhartmann commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/persistence/PolicyPersistence.java
> +        if (bpns == null) {
Do I understand it right, that this is the case, where no BPNs were provided when registering the policy, so they will be added to the default blob?

2024-03-12 16:21 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/policy/PolicyCheckerService.java
> +        return policyStore.getAcceptedPolicies(bpn == null ? null : List.of(bpn))
is this really correct? 
From my understanding the policies without a BPN aka the policies in DEFAULT_BLOB_NAME should be used in every validation and additionally the policies for the provided BPN.
This BPN should never be null since we always have a BPN for which we try to negotiate

2024-03-13 11:09 UTC, ds-psosnowski commented on irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/DefaultConfiguration.java
> +                return facade.getEndpointReferencesForAsset(edcConnectorEndpoint, assetType, assetValue, null);
it is null se default policies will be used (we don't have access to bpn here)

2024-03-13 11:10 UTC, ds-psosnowski commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/persistence/PolicyPersistence.java
> +        if (bpns == null) {
exactly, this was requirement from story that if bpn is null then it should go as default

2024-03-13 11:11 UTC, ds-psosnowski commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/policy/PolicyCheckerService.java
> +        return policyStore.getAcceptedPolicies(bpn == null ? null : List.of(bpn))
if this is null then default will be used

2024-03-13 12:18 UTC, dsmf requested changes

2024-03-13 12:18 UTC, dsmf commented on irs-policy-store/src/test/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreServiceTest.java
> +    void shouldThrowException() {
@ds-psosnowski empty test?

2024-03-13 12:56 UTC, ds-psosnowski commented on irs-policy-store/src/test/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreServiceTest.java
> +    void shouldThrowException() {
I was testing test coverage and uploaded it by mistake, clearing up in a second

2024-03-13 17:33 UTC, dsmf requested changes
Hi @ds-psosnowski, please see my review comments. For my specific code suggestions have a look at https://github.com/catenax-ng/tx-item-relationship-service/tree/feature/%23199-register-policy-definition-for-certian-bpnls--REVIEW please.

2024-03-13 17:33 UTC, dsmf commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/persistence/PolicyPersistence.java
> +                    return new AbstractMap.SimpleEntry<>(entry.getKey(),
Hi @ds-psosnowski , would be good to have entry.getKey() in a local temporary variable with a speaking name that explains what the entry key is from a business perspective.

2024-03-13 17:33 UTC, dsmf commented on irs-common/src/main/java/org/eclipse/tractusx/irs/common/persistence/BlobPersistence.java
> +    Map<String, byte[]> getAllBlobs() throws BlobPersistenceException;
Hi @ds-psosnowski , 
Please document the return type via javadoc because Map<String, byte[]> leaves the reader wondering what the map key actually is.

2024-03-13 17:33 UTC, dsmf commented on irs-policy-store/src/test/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreServiceTest.java
> -    void updatePolicyShouldThrowResponseStatusException() {
Hi @ds-psosnowski , test was removed without respective replacement?

2024-03-13 17:50 UTC, dsmf commented
Hi @ds-psosnowski , in the concept in the story there is a "PUT /irs/policy/{policyId}" but I cannot find this in the implementation. We just have PUT "/irs/policies/{policyId}" (plural). Is the concept just inconsistent here or is anything missing in the implementation / incorrectly implemented?!

2024-03-13 17:56 UTC, dsmf commented
Hi @ds-psosnowski , another thing I am wondering about:

the concept says "API GET /irs/policies" (with a request parameter). But the implementation has "API GET /irs/policies/{bpns}", meaning that the BPNs are passed as path parameter. Never seen an array being passed as path parameter before. Is this correct? 
I meant it would be an URL in the following form:

` GET /irs/policies/BPN1,BPN2,BPN3 `

intended?

2024-03-14 09:01 UTC, ds-psosnowski commented
Hey, please comment out code so I can reply in relevant topics. According to:
1. list of bpns in path param - this is get request so you cannot have body for it also array is perfectly fine as parameter. If for some reason we don't want that this method need to be converted to post for example. 
There is business partner number when you query for all policies. If you are not (you are passing the bpn as param) then there is no need to return it since you are returning polices for given bnps right? 
About return type - original get was returning whole policy not just an id, I don't think it would make sense to return only id's for policies that are for some bpns and whole policy when we use getAll, I believe this is mistake in story definition, but we can confirm it.
2. ../policy/... or .../policies/... - do you really think that it was intended to use singular only for one request? I would rather think that this is just typo

2024-03-14 09:11 UTC, ds-psosnowski commented on irs-policy-store/src/test/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreServiceTest.java
> -    void updatePolicyShouldThrowResponseStatusException() {
Test is not relevant anymore since update method is replaced

2024-03-14 09:12 UTC, ds-psosnowski commented on irs-common/src/main/java/org/eclipse/tractusx/irs/common/persistence/BlobPersistence.java
> +    Map<String, byte[]> getAllBlobs() throws BlobPersistenceException;
good point

2024-03-14 09:49 UTC, ds-psosnowski commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/controllers/PolicyStoreController.java
> +        request.policiesIds().forEach(policyId -> service.updatePolicy(policyId, request));
this is very good point

2024-03-15 17:12 UTC, dsmf commented
merged main again because of new conflict

2024-03-20 23:45 UTC, dsmf requested changes
Hi @ds-psosnowski and @ds-jhartmann , 

There are open questions concerning the "default" and why apiAllowedBpn was removed. This may be fine, but I simply don't understand this. Maybe you can clarify this?

2024-03-20 23:45 UTC, dsmf commented on irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/persistence/PolicyPersistence.java
> +                    return new AbstractMap.SimpleEntry<>(entry.getKey(),
looks good to me now

2024-03-20 23:45 UTC, dsmf commented on irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RegistryConfiguration.java
> +                        return facade.getEndpointReferencesForAsset(edcConnectorEndpoint, assetType, assetValue, null);
Hi @ds-psosnowski, you use "default" instead of the null now. But how does it work actually? Did you introduce the value "default"? What happens actually if one passes "default"?

2024-03-20 23:45 UTC, dsmf commented on charts/irs-helm/templates/configmap-spring-app-config.yaml
> -    apiAllowedBpn: {{ tpl (.Values.bpn | default "") . | quote }}
Hi @ds-psosnowski, what's the connection to the story. Why was this removed?

2024-03-21 08:20 UTC, ds-psosnowski commented on charts/irs-helm/templates/configmap-spring-app-config.yaml
> -    apiAllowedBpn: {{ tpl (.Values.bpn | default "") . | quote }}
apiAllowedBpn was the only bpn that we saved policies for, right now we pass the bpn or if it is null we saved it under default in storage (this is also used when we use default (previously null) - we use default policies)

2024-03-21 08:24 UTC, ds-psosnowski commented on charts/irs-helm/templates/configmap-spring-app-config.yaml
> -    apiAllowedBpn: {{ tpl (.Values.bpn | default "") . | quote }}
About the "Something similar like my suggestion above in PolicyPersistence?" comment - it is described in implementation, this is the interface method, do you think it should be commented in both? I've already mentioned it before

2024-03-21 13:08 UTC, dsmf approved these changes
Clarified apiAllowedBpn and default handling with @ds-psosnowski via msteams. Makes sense to me now. Therefore approved from my side.

2024-03-22 12:34 UTC, ds-jhartmann approved these changes
LGTM

2024-03-22 12:47 UTC, merged