Fix/448 missing timeouts
catenax-ng/tx-item-relationship-service pull request #808
Opened 2024-03-07 18:14 UTC by dsmf

just draft PR, not complete yet

2024-03-15 14:22 UTC, ds-jhartmann requested changes

2024-03-15 14:22 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcConfiguration.java
> +    private Duration asyncTimeout = Duration.ofMinutes(ASYNC_TIMEOUT_MINUTES_DEFAULT);
Am I missing something or is the value from application.yaml never used? Only the statically configured value ASYNC_TIMEOUT_MINUTES_DEFAULT

2024-03-15 16:05 UTC, dsmf commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcConfiguration.java
> +    private Duration asyncTimeout = Duration.ofMinutes(ASYNC_TIMEOUT_MINUTES_DEFAULT);
This initialization is for the unit tests because there the application.properties is not loaded => npe.
Tested it in a spring boot test via debugging that the value gets overridden by the configured value.

2024-03-18 07:47 UTC, ds-jhartmann commented on irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/EdcConfiguration.java
> +    private Duration asyncTimeout = Duration.ofMinutes(ASYNC_TIMEOUT_MINUTES_DEFAULT);
Thanks for the clarification :)

2024-03-18 07:47 UTC, ds-jhartmann approved these changes
LGTM

2024-03-18 09:04 UTC, merged